version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: edeeron-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rootpassw
        - MYSQL_DATABASE=Edeeron_db01
        - MYSQL_USER=Edeeron_u01
        - MYSQL_PASSWORD=3d33r0n
      ports:
        - "7901:3306"

    webserver:
      image: nginx:alpine
      container_name: edeeron-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7899:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: edeeron-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

